-- Database: postgres

-- DROP DATABASE postgres;

CREATE DATABASE postgres
    WITH 
    OWNER = "ManojYeddanapudy"
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE postgres
    IS 'default administrative connection database';

GRANT ALL ON DATABASE postgres TO newuser;

GRANT TEMPORARY, CONNECT ON DATABASE postgres TO PUBLIC;

GRANT ALL ON DATABASE postgres TO "ManojYeddanapudy";

-- SCHEMA: finalproject

-- DROP SCHEMA finalproject ;

CREATE SCHEMA finalproject
    AUTHORIZATION "ManojYeddanapudy";

GRANT ALL ON SCHEMA finalproject TO "ManojYeddanapudy";

GRANT USAGE ON SCHEMA finalproject TO newuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA finalproject
GRANT ALL ON TABLES TO "ManojYeddanapudy";


-- Table: finalproject.project

-- DROP TABLE finalproject.project;

CREATE TABLE finalproject.project
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 0 MINVALUE 0 MAXVALUE 2147483647 CACHE 1 ),
    tv_show character(50) COLLATE pg_catalog."default",
    review character(250) COLLATE pg_catalog."default",
    review_date date DEFAULT CURRENT_DATE,
    CONSTRAINT project_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE finalproject.project
    OWNER to "ManojYeddanapudy";

GRANT ALL ON TABLE finalproject.project TO "ManojYeddanapudy";

GRANT ALL ON TABLE finalproject.project TO newuser;

